### ISSUE TITLE
Log exception tracebacks

### ISSUE THREAD

**Issue by bnaul** [cesium-ml/cesium_web#179]
I believe @stefanv mentioned this already but I didn't see an issue; when a Python application error occurs, the text of the exception gets logged but not any of the context. So for example you'll see:
```
APP ERROR: name 'np' is not defined
```
...which isn't particularly helpful. We should definitely at least print the location where the exception was raised, and possibly some of the stack trace as well.

**Comment by stefanv** [comment]
This is fixed on my `multi-user` branch (see https://github.com/cesium-ml/cesium_web/pull/175).

**Comment by bnaul** [comment]
@stefanv I still don't see any logs for some exceptions: specifically I've found that anything in a coroutine (e.g. `_await_model_statistics`) just displays an error on the frontend but it's never recorded anywhere. Any idea why?

**Comment by stefanv** [comment]
The error is caught and not printed.  See `_await_featurization`---that one should work.

**Comment by stefanv** [comment]
See also https://github.com/cesium-ml/cesium_web/pull/205
